In [1]:
import pandas as pd

* head()
* tail()
* isin()
* isna()
* sum()
* mean()
* min()
* max()
* var()
* std()
* median()
* mode()
* quantile()
* describe()
* info()
* value_counts()
* count()
* drop_duplicates()
* sample()
* replace()
* equals()
* cummax()
* cummin()
* cumsum()
* cumprod()
* diff()
* sort_index()
* sort_values()
* nlargest()
* nsmallest()

In [2]:
df = pd.DataFrame(data={"id": [101, 102, 103,104,105,106,101], "name": ["张三", "李四", "王五","赵六","冯七","周八","张三"], "age": [10, 20, 30, 40, None, 60,10]},index=["aa", "bb", "cc", "dd", "ee", "ff","aa"])
df

     id name   age
aa  101   张三  10.0
bb  102   李四  20.0
cc  103   王五  30.0
dd  104   赵六  40.0
ee  105   冯七   NaN
ff  106   周八  60.0
aa  101   张三  10.0

In [4]:
df.isin([103,106])

       id   name    age
aa  False  False  False
bb  False  False  False
cc   True  False  False
dd  False  False  False
ee  False  False  False
ff   True  False  False
aa  False  False  False

In [5]:
df.isna()

       id   name    age
aa  False  False  False
bb  False  False  False
cc  False  False  False
dd  False  False  False
ee  False  False   True
ff  False  False  False
aa  False  False  False

In [7]:
df.min()

id       101
name      冯七
age     10.0
dtype: object

In [10]:
df["age"].quantile(0.5)

np.float64(25.0)

In [8]:
df["age"].quantile(0.5)

   A  B
0  2  1
2  3  2
4  4  3
1  5  6
3  7  8

In [11]:
df.describe()

               id        age
count    7.000000   6.000000
mean   103.142857  28.333333
std      1.951800  19.407902
min    101.000000  10.000000
25%    101.500000  12.500000
50%    103.000000  25.000000
75%    104.500000  37.500000
max    106.000000  60.000000

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7 entries, aa to aa
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      7 non-null      int64
 1   name    7 non-null      object
 2   age     6 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 224.0+ bytes

In [13]:
df["age"].info()

<class 'pandas.core.series.Series'>
Index: 7 entries, aa to aa
Series name: age
Non-Null Count  Dtype
--------------  -----
6 non-null      float64
dtypes: float64(1)
memory usage: 112.0+ bytes

In [14]:
df.value_counts()

id   name  age
101  张三    10.0    2
102  李四    20.0    1
103  王五    30.0    1
104  赵六    40.0    1
106  周八    60.0    1
Name: count, dtype: int64

In [15]:
df

     id name   age
aa  101   张三  10.0
bb  102   李四  20.0
cc  103   王五  30.0
dd  104   赵六  40.0
ee  105   冯七   NaN
ff  106   周八  60.0
aa  101   张三  10.0

In [16]:
df.count()

id      7
name    7
age     6
dtype: int64

In [18]:
df.nunique()

id      6
name    6
age     5
dtype: int64

In [20]:
type(df.nunique())

pandas.core.series.Series

In [19]:
df['age'].unique()

array([10., 20., 30., 40., nan, 60.])

In [21]:
df.drop_duplicates()

     id name   age
aa  101   张三  10.0
bb  102   李四  20.0
cc  103   王五  30.0
dd  104   赵六  40.0
ee  105   冯七   NaN
ff  106   周八  60.0

In [22]:
df.sort_index()

     id name   age
aa  101   张三  10.0
aa  101   张三  10.0
bb  102   李四  20.0
cc  103   王五  30.0
dd  104   赵六  40.0
ee  105   冯七   NaN
ff  106   周八  60.0

In [25]:
df.sort_values(
    by=['age'],
    ascending=[True]
)

     id name   age
aa  101   张三  10.0
aa  101   张三  10.0
bb  102   李四  20.0
cc  103   王五  30.0
dd  104   赵六  40.0
ff  106   周八  60.0
ee  105   冯七   NaN

In [26]:
df.replace('张三',456)

     id name   age
aa  101  456  10.0
bb  102   李四  20.0
cc  103   王五  30.0
dd  104   赵六  40.0
ee  105   冯七   NaN
ff  106   周八  60.0
aa  101  456  10.0

In [27]:
df.nlargest(n=2,columns='age')

     id name   age
ff  106   周八  60.0
dd  104   赵六  40.0

In [28]:
df['age'].nlargest(3)

ff    60.0
dd    40.0
cc    30.0
Name: age, dtype: float64