In [1]:
import pandas as pd

In [2]:
df1 = pd.DataFrame(
 data={"age": [10, 20, 30, 40], "name": ["张三", "李四", "王五", "赵六"]},
 columns=["name", "age"],
 index=[101, 102, 103, 104],
)
df2 = pd.DataFrame(
 data={"age": [10, 20, 30, 40], "name": ["张三", "李四", "王五", "田七"]},
 columns=["name", "age"],
 index=[102, 103, 104, 105],
)
df1

    name  age
101   张三   10
102   李四   20
103   王五   30
104   赵六   40

In [3]:
df2

    name  age
102   张三   10
103   李四   20
104   王五   30
105   田七   40

In [4]:
print(df1 + df2)

     name   age
101   NaN   NaN
102  李四张三  30.0
103  王五李四  50.0
104  赵六王五  70.0
105   NaN   NaN

TypeError: can only concatenate str (not "int") to str